name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        pip install uv

    - name: Install project
      run: |
        uv pip install --system -e packages/runtime-sdk -e packages/cli
        uv pip install --system --group dev --project packages/cli

    # TODO: cli tests include running sdks in workerd.
    # Since running workerd tests has mostly nothing to do with the host python versions,
    # we don't need to run them for all python versions.
    - name: Run tests
      working-directory: packages/cli
      run: |
        pytest -v --color=yes tests

    - name: Verify that pywrangler can be run globally
      run: |
        pywrangler --help
